
package com.coda.airtime.ws.airtime.api1_0;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-08-23T09:52:44.304-07:00
 * Generated source version: 2.6.2
 * 
 */
public final class Payment_Api_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.airtime.coda.com/airtime/api1.0", "soap-v1.0");

    private Payment_Api_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CodaAPI.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CodaAPI ss = new CodaAPI(wsdlURL, SERVICE_NAME);
        Payment port = ss.getApi();  
        
        {
        System.out.println("Invoking init...");
        com.coda.airtime.ws.airtime.api1.InitRequest _init_arg0 = null;
        com.coda.airtime.ws.airtime.api1.InitResult _init__return = port.init(_init_arg0);
        System.out.println("init.result=" + _init__return);


        }
        {
        System.out.println("Invoking inquiryPaymentResult...");
        com.coda.airtime.ws.airtime.api1.InquiryPaymentRequest _inquiryPaymentResult_arg0 = null;
        com.coda.airtime.ws.airtime.api1.PaymentResult _inquiryPaymentResult__return = port.inquiryPaymentResult(_inquiryPaymentResult_arg0);
        System.out.println("inquiryPaymentResult.result=" + _inquiryPaymentResult__return);


        }

        System.exit(0);
    }

}
