package com.coda.airtime.ws.airtime.api1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2012-08-23T09:52:44.352-07:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://ws.airtime.coda.com/airtime/api1.0", name = "Payment")
@XmlSeeAlso({com.coda.airtime.ws.airtime.api1.ObjectFactory.class})
public interface Payment {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "init", targetNamespace = "http://ws.airtime.coda.com/airtime/api1.0", className = "com.coda.airtime.ws.airtime.api1.Init")
    @WebMethod
    @ResponseWrapper(localName = "initResponse", targetNamespace = "http://ws.airtime.coda.com/airtime/api1.0", className = "com.coda.airtime.ws.airtime.api1.InitResponse")
    public com.coda.airtime.ws.airtime.api1.InitResult init(
        @WebParam(name = "arg0", targetNamespace = "")
        com.coda.airtime.ws.airtime.api1.InitRequest arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "inquiryPaymentResult", targetNamespace = "http://ws.airtime.coda.com/airtime/api1.0", className = "com.coda.airtime.ws.airtime.api1.InquiryPaymentResult")
    @WebMethod
    @ResponseWrapper(localName = "inquiryPaymentResultResponse", targetNamespace = "http://ws.airtime.coda.com/airtime/api1.0", className = "com.coda.airtime.ws.airtime.api1.InquiryPaymentResultResponse")
    public com.coda.airtime.ws.airtime.api1.PaymentResult inquiryPaymentResult(
        @WebParam(name = "arg0", targetNamespace = "")
        com.coda.airtime.ws.airtime.api1.InquiryPaymentRequest arg0
    );
}
